apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: kserve-models-web-app
spec:
  rules:
    - from:
        - source:
            principals:
              - cluster.local/ns/{{ istio.gateway.namespace }}/sa/{{ istio.gateway.serviceAccount }}
