vars:
  - file: config/auth-defaults.yaml
  - file: config/users-defaults.yaml
  - file: "{{ args.config }}"
    when: args.config
  - file: config/check-errors.yaml

deployments:
  - path: ../../common
    onlyRender: true
  - path: ../../apps
    onlyRender: true
  - path: ../../contrib/kserve
    onlyRender: true
  - include: common
  - barrier: true
  - include: apps
  - barrier: true
  - include: users

conflictResolution:
  - kind: ValidatingWebhookConfiguration
    fieldPath:
    - webhooks.*.rules
    - webhooks.*.failurePolicy
    action: ignore
  - kind: MutatingWebhookConfiguration
    fieldPath: webhooks.*.rules
    action: ignore
  - manager: clusterrole-aggregation-controller
    action: ignore
  - manager: cert-manager-cainjector
    action: ignore
