vars:
  - file: config/auth-defaults.yaml
  - file: "{{ args.config }}"
    when: args.config
  - file: config/check-errors.yaml

deployments:
  - path: ../../common
    onlyRender: true
  - path: ../../apps
    onlyRender: true
  - path: ../../contrib/kserve
    onlyRender: true
  - include: common
  - barrier: true
  - include: apps
