apiVersion: v1
kind: ConfigMap
metadata:
  name: config-istio
  namespace: knative-serving
data:
  gateway.kubeflow.kubeflow-gateway: {{ istio.gateway.serviceName }}.{{ istio.gateway.namespace }}.svc.cluster.local
