deployments:
  # Cert-Manager
  - include: cert-manager
    when: cert_manager.enabled
  - barrier: true
  - path: ../../../common/cert-manager/kubeflow-issuer/base
  # Istio
  - include: istio
    when: istio.enabled
  - barrier: true
  # oauth2-proxy
  - path: ../../../common/oidc-client/oauth2-proxy/overlays/kluctl
    when: auth.oauth2_proxy.enabled
    tags:
      - oauth2-proxy
  # auth-service
  - path: ../../../common/oidc-client/oidc-authservice/overlays/kluctl
    when: auth.auth_service.enabled
    tags:
      - auth-service
  # Dex
  - path: ../../../common/dex/overlays/kluctl
  # KNative
  - path: ../../../common/knative/knative-serving/overlays/kluctl
  - path: ../../../common/knative/knative-eventing/base
  - path: ../../../common/istio-1-17/cluster-local-gateway/base
  # Kubeflow namespace
  - path: ../../../common/kubeflow-namespace/base
    tags:
      - kubeflow-namespace
  # Kubeflow Roles
  - path: ../../../common/kubeflow-roles/base
    tags:
      - kubeflow-roles
  # Kubeflow Istio Resources
  - path: ../../../common/istio-1-17/kubeflow-istio-resources/overlays/kluctl
    tags:
      - kubeflow-istio-resources

conflictResolution:
  # We should ignore the conflict that is created by the configure-self-signed-kubernetes-oidc-issuer Job
  - kind: RequestAuthentication
    name: m2m-token-issuer
    fieldPath: spec.jwtRules
    action: ignore
