deployments:
  # Cert-Manager
  - path: ../../../common/cert-manager/cert-manager/base
  - waitReadinessObjects:
      - kind: Deployment
        name: cert-manager-webhook
        namespace: cert-manager
  - barrier: true
  - path: ../../../common/cert-manager/kubeflow-issuer/base
  # Istio
  - path: ../../../common/istio-1-17/istio-crds/base
  - path: ../../../common/istio-1-17/istio-namespace/base
  # istio CRDs and NS can be deployed in parallel
  - barrier: true
  - path: ../../../common/istio-1-17/istio-install/overlays/oauth2-proxy
  - barrier: true
  # oauth2-proxy
  - path: ../../../common/oidc-client/oauth2-proxy/overlays/m2m-self-signed
  - path: ../../../common/dex/overlays/oauth2-proxy
  # KNative
  - path: ../../../common/knative/knative-serving/overlays/gateways
  - path: ../../../common/knative/knative-eventing/base
  - path: ../../../common/istio-1-17/cluster-local-gateway/base
  # Kubeflow namespace
  - path: ../../../common/kubeflow-namespace/base
  # Kubeflow Roles
  - path: ../../../common/kubeflow-roles/base
  # Kubeflow Istio Resources
  - path: ../../../common/istio-1-17/kubeflow-istio-resources/base
