deployments:
  # Cert-Manager
  - path: ../../../common/cert-manager/cert-manager/base
  - waitReadinessObjects:
      - kind: Deployment
        name: cert-manager-webhook
        namespace: cert-manager
  - barrier: true
  - path: ../../../common/cert-manager/kubeflow-issuer/base
  # Istio
  - path: ../../../common/istio-1-17/istio-crds/base
  - path: ../../../common/istio-1-17/istio-namespace/base
  # istio CRDs and NS can be deployed in parallel
  - barrier: true
  - path: ../../../common/istio-1-17/istio-install/overlays/kluctl
  - barrier: true
  # oauth2-proxy
  - path: ../../../common/oidc-client/oauth2-proxy/overlays/kluctl
    when: auth.oauth2_proxy.enabled
  # auth-service
  - path: ../../../common/oidc-client/oidc-authservice/base
    when: auth.auth_service.enabled
  # Dex
  - path: ../../../common/dex/overlays/kluctl
  # KNative
  - path: ../../../common/knative/knative-serving/overlays/gateways
  - path: ../../../common/knative/knative-eventing/base
  - path: ../../../common/istio-1-17/cluster-local-gateway/base
  # Kubeflow namespace
  - path: ../../../common/kubeflow-namespace/base
    tags:
      - kubeflow-namespace
  # Kubeflow Roles
  - path: ../../../common/kubeflow-roles/base
    tags:
      - kubeflow-roles
  # Kubeflow Istio Resources
  - path: ../../../common/istio-1-17/kubeflow-istio-resources/base
    tags:
      - kubeflow-istio-resources

conflictResolution:
  # We should ignore the conflict that is created by the configure-self-signed-kubernetes-oidc-issuer Job
  - kind: RequestAuthentication
    name: m2m-token-issuer
    fieldPath: spec.jwtRules
    action: ignore
